services:
  - type: web
    name: smyrna-cms
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: "./server/smyrna.db"
    autoDeploy: true
